BOOTLOADER = atmel-dfu
DEFAULT_FOLDER = ferris/sweep

RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes

LTO_ENABLE = yes

SRC += features/achordion.c
